CREATE OR REPLACE VIEW DML_LOG
AS
WITH T AS (
SELECT AH.QUERY_ID,QH.QUERY_TEXT,QH.START_TIME,QH.END_TIME,AH.OBJECTS_MODIFIED,QH.QUERY_TYPE,QH.USER_NAME LAST_DML_BY,
QH.ROWS_INSERTED,QH.ROWS_UPDATED,QH.ROWS_DELETED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY AH
INNER JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY QH
ON AH.QUERY_ID =QH.QUERY_ID 
WHERE QH.QUERY_TYPE IN ('UPDATE','MERGE','INSERT','MULTI_TABLE_INSERT','DML')
),
TABLES_DML AS (
SELECT END_TIME LAST_DML,
LAST_DML_BY,ROWS_INSERTED,ROWS_UPDATED,ROWS_DELETED,
F1.VALUE:"objectName"::VARCHAR TABLE_NAME_FULL,T.QUERY_ID,T.QUERY_TYPE,T.QUERY_TEXT,
SPLIT_PART(TABLE_NAME_FULL,'.',1) TABLE_CATALOG,
SPLIT_PART(TABLE_NAME_FULL,'.',2) TABLE_SCHEMA,
SPLIT_PART(TABLE_NAME_FULL,'.',3) TABLE_NAME
  FROM T
      ,LATERAL FLATTEN(T.OBJECTS_MODIFIED) F1
 WHERE F1.VALUE:"objectDomain"::VARCHAR = 'Table'
QUALIFY END_TIME = MAX(END_TIME) OVER (PARTITION BY QUERY_ID,TABLE_NAME_FULL) -- IF we have MORE OBJECTS modified ON the TABLE, we ONLY want the LAST one
)
SELECT  TDML.QUERY_ID, TDML.QUERY_TYPE,TDML.QUERY_TEXT, TDML.TABLE_CATALOG, TDML.TABLE_SCHEMA, TDML.TABLE_NAME, 
TABLE_OWNER,TABLE_TYPE,IS_TRANSIENT, TB.ROW_COUNT ROW_COUNT_BEFORE_DROP, 
TDML.ROWS_INSERTED ROWS_INSERTED_DML,TDML.ROWS_UPDATED ROWS_UPDATED_DML,
TDML.ROWS_DELETED ROWS_DELETED_DML,TDML.LAST_DML_BY,TDML.LAST_DML
FROM TABLES_DML TDML  
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE."TABLES" TB
ON TB.TABLE_CATALOG = TDML.TABLE_CATALOG 
 AND TB.TABLE_SCHEMA = TDML.TABLE_SCHEMA 
 AND TB.TABLE_NAME = TDML.TABLE_NAME
    AND TDML.LAST_DML BETWEEN TB.CREATED AND COALESCE(TB.DELETED ,CURRENT_TIMESTAMP())
ORDER BY LAST_DML DESC;